# Generated by Django 3.2.3 on 2021-05-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('FL', 'Цветы'), ('DO', 'Веснушки'), ('WO', 'Слова'), ('AN', 'Животные'), ('OT', 'Другое'), ('ON', 'Однушки'), ('SE', 'Наборы')], max_length=2)),
                ('image', models.FileField(upload_to='images/')),
            ],
        ),
    ]
