# Generated by Django 3.2.3 on 2021-05-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='sale_price',
            field=models.IntegerField(null=True),
        ),
    ]
