# Generated by Django 3.2.3 on 2021-05-27 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_position_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='position',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cart'),
        ),
    ]
