# Generated by Django 3.2.3 on 2021-05-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_cart_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
