# Generated by Django 3.2.3 on 2021-05-27 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cart_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='position',
            name='cart',
        ),
        migrations.CreateModel(
            name='CartPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cart')),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.position')),
            ],
        ),
    ]
