# Generated by Django 3.2.3 on 2021-05-28 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210527_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartposition',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.position'),
        ),
    ]
