# Generated by Django 3.2.3 on 2021-05-28 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cartposition_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('profit_percent', models.IntegerField()),
                ('expiry', models.DateTimeField(default=datetime.datetime(2021, 6, 27, 3, 50, 58, 55423))),
                ('once', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
